import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from './components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' />
      </head>
      <body className={inter.className}>
        <NavBar />
        <div className='body-content'>
          {children}
        </div>
      </body>

    </html>
  )
}
